### ISSUE TITLE
Logging failing to encode international characters

### ISSUE THREAD

**Issue by dGameBoy101b** [dGameBoy101b/Audio-Ripper#1]
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\audio_scanner.py", line 104, in try_get_next_path
    self.__current_path = next(self.__scanner)
                          ^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 132-135: character maps to <undefined>
Call stack:
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\rhysm\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\rhysm\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\rhysm\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 384, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "c:\Users\rhysm\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 228, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "c:\Users\rhysm\.vscode\extensions\ms-python.debugpy-2024.14.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\gui\__main__.py", line 2, in <module>
    main()
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\gui\audio_ripper_gui.py", line 64, in main
    app.mainloop()
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1485, in mainloop
    self.tk.mainloop(n)
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\gui\directory_scans_frame.py", line 85, in add_directory
    self.__layout_items()
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\gui\directory_scans_frame.py", line 131, in __layout_items
    self.update()
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1370, in update
    self.tk.call('update')
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
  File "c:\Users\rhysm\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\gui\recurring_tkinter_task.py", line 33, in __run
    self.callback()
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\gui\directory_scans_frame.py", line 196, in __continue_scan
    self.scanner.continue_scan()
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\audio_scanner.py", line 116, in continue_scan
    if not self.try_get_next_path():
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\audio_scanner.py", line 107, in try_get_next_path
    self.close_current_directory()
  File "C:\Users\rhysm\Documents\Python Projects\audio_ripper\audio_scanner.py", line 141, in close_current_directory
    logger.info(f'closed directory: {fspath(self.__current_directory)}')
Message: 'closed directory: C:/Users/rhysm/Music/iTunes/iTunes Media/Music/Camellia (かめりあ)\\Beat Saber OST Vol. 5'
Arguments: ()
```

**Comment by dGameBoy101b** [comment]
That same message prints fine to the console

**Comment by dGameBoy101b** [comment]
Reducing the strictness of the file handler seems to have no effect.
```python
		'file':{
			'class': 'logging.FileHandler',
			'formatter': 'default',
			'level': DEBUG,
			'filename': join(dirname(__file__), 'rip.log'),
			'mode' : 'w',
			'filters':[
				'not_ffprobe'
			],
			'encoding': 'utf-8',
			'errors': 'replace'
```
